import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next Parallal Routes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  header,
  sider
}: Readonly<{
  children: React.ReactNode,
  header:React.ReactNode,
  sider:React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
      className="bg-gray-100"
      >
        {header}
        <div className="flex">
          {sider}
          <main className="flex-1 p-6">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
